### ISSUE TITLE
Jumpy touchpad issue when using two fingers (For example when drag and dropping a file or an Application from Launchpad to the Dock)

### ISSUE THREAD

**Issue by throwaway29292** [PIut02/ROG-Zephyrus-G14-GA401IV-Hackintosh#17]
Hi, i noticed a weird issue with the EFI concerning the touchpad movement. When i use one finger to click on the left button and then use the other finger to move something around the screen, the movement becomes very jumpy. In particular the item jumps to upper left corner whenever i lift and place the finger again. When i test it by just tapping the touchpad with the other finger, i can see the cursor jumping to random places. On windows, the cursor stays in the same position and only rarely moves slightly.

I first thought, that disabling "tap to touch" in touchpad options solved it, however it still happens randomly for ~10 seconds before stopping for some time. For example, try moving a file in Finder from one folder to another by drag and dropping and you should see what i mean.

I had this problem both on Ventura and Sonoma. Interestingly, i had the same issue on older Asus Zenbook with Kaby Lake CPU, that i created my own EFI for.

**Comment by PIut02** [comment]
Interestingly, I tried it and didn't find the issue, regardless of whether "tap to touch" is on or not.
